spring.kafka.bootstrap-servers=kafka:9092
# ?????? ????????? ?????????, ???? ??? ???? ? ProducerFactory
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# spring.kafka.producer.properties.spring.json.add.type.headers=false
# spring.kafka.producer.properties.spring.json.trusted.packages=*
# spring.kafka.producer.properties.spring.json.value.default.type=com.example.userservice.event.UserEvent